export const LOGIN_FETCH_REQUEST = "LOGIN_FETCH_REQUEST";
export const LOGIN_FETCH_SUCCESS = "LOGIN_FETCH_SUCCESS";
export const LOGIN_FETCH_FAILURE = "LOGIN_FETCH_FAILURE";

// ONE_FETCH_REQUEST = "ONE_FETCH_REQUEST";
// ONE_FETCH_SUCCESS = "ONE_FETCH_SUCCESS";
// ONE_FETCH_FAILURE = "ONE_FETCH_FAILURE";
// ONE_SAVE_REQUEST = "ONE_SAVE_REQUEST";
// ONE_SAVE_SUCCESS = "ONE_SAVE_SUCCESS";
// ONE_SAVE_FAILURE = "ONE_SAVE_FAILURE";
// ONE_DELETE_REQUEST = "ONE_DELETE_REQUEST";
// ONE_DELETE_SUCCESS = "ONE_DELETE_SUCCESS";
// ONE_DELETE_FAILURE = "ONE_DELETE_FAILURE";
